@startuml state_diagram

' [*] -->  Initialization : Init

state Initialization {
    Initialization: entry
    Initialization: do / Initialize internal parameters
    Initialization: exit
}

Initialization --> Operational


state Operational {
    Operational: entry / greenLEDon
    Operational: do / Normal input-output behavior
    Operational: exit / greenLEDOff
}

Operational --> Initialization : reset
@enduml