@startuml state_diagram

' [*] -->  Initialization : Init

state Initialization {
    Initialization: entry / Initialize internal parameters
    ' Initialization: do
    Initialization: exit /  Boot-up message
}

Initialization --> Operational

state Operational {
    Operational: entry / greenLEDon
    Operational: do / Run motor
    Operational: exit / greenLEDOff
}

Operational --> Initialization : reset
@enduml