@startuml state_diagram

' [*] -->  Initialization : Init

state Initialization {
    Initialization: entry / Initialize internal parameters
    ' Initialization: do
    Initialization: exit /  Boot-up message
}

Initialization --> PreOperational

state PreOperational {
    PreOperational: entry / Blink Yellow LED at 1 Hz
    PreOperational: do / Accept configuration commands
    PreOperational: exit / Turn yellow LED off
}

PreOperational --> Stopped : emergency stop
Stopped --> PreOperational : clear fault
PreOperational --> Operational : Set operational
PreOperational --> Initialization : reset

state Operational {
    Operational: entry / Turn green LED on
    Operational: do / Run motor
    Operational: exit / Turn green LED off
}

Operational --> PreOperational : Set pre-operational

state Stopped {
    Stopped: entry / Stop motor
    Stopped: do / Blink red LED at 2 Hz
    Stopped: exit / Turn red LED off
}

Operational --> Stopped : emergency stop
Stopped --> Operational : clear fault
Stopped --> Initialization : reset
Operational --> Initialization : reset
@enduml